version: "3"
services:
  api:
    image: idealpostcodes/postcodes.io:latest
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - db
    environment:
      - POSTGRES_DATABASE=postcodesiodb
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=postcodesio
      - POSTGRES_HOST=db
    ports:
      - "8000:8000"
    networks:
      lab-subset:
        ipv4_address: 172.16.106.57

  db:
    image: idealpostcodes/postcodes.io.db:latest
    restart: unless-stopped
    environment:
      - POSTGRES_DB=postcodesiodb
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=postcodesio
    networks:
      lab-subset:
        ipv4_address: 172.16.106.58

networks:
  lab-subset:
    external: true
